---
- name: Install Docker
  ansible.builtin.package:
    name: docker.io
    state: present

- name: Install minikube
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Set default driver to Docker
  ansible.builtin.command:
    cmd: minikube config set driver docker
  changed_when: true

- name: Ensure Docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add Ansible user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Reset SSH connection to apply group membership
  ansible.builtin.meta: reset_connection

- name: Create application directory
  ansible.builtin.file:
    path: /opt/sre-challenge/app
    state: directory
    owner: root
    group: root
    mode: '0755'
  
- name: Copy application files
  ansible.builtin.copy:
    src: app/
    dest: /opt/sre-challenge/app
    owner: root
    group: root
    mode: '0644'

- name: Create scripts directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/scripts
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Place minikube script
  ansible.builtin.copy:
    src: files/scripts/minikube.sh
    dest: /home/{{ ansible_user }}/scripts/minikube.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  notify: restart minikube service

- name: Make application run by systemd service
  ansible.builtin.template:
    src: files/scripts/minikube.service.j2
    dest: /etc/systemd/system/minikube.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart minikube service

- name: Enable and start the application service
  ansible.builtin.systemd:
    name: minikube.service
    state: started
    enabled: true
    daemon_reload: yes
  become: true

- name: Copy dockerfile
  ansible.builtin.copy:
    src: docker/dockerfile
    dest: /opt/sre-challenge/Dockerfile
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: true

- name: Build SRE challenge Docker image
  ansible.builtin.command:
    cmd: docker build -t sre-challenge:1.0 .
    chdir: /opt/sre-challenge
  become: true
  become_user: "{{ ansible_user }}"
  register: docker_build

- name: Load SRE challenge image into Minikube
  ansible.builtin.command:
    cmd: minikube image load sre-challenge:1.0
  become: false
  register: minikube_image_load

- name: copy kubernetes manifests
  ansible.builtin.copy:
    src: kubernetes/
    dest: /opt/sre-challenge/kubernetes/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Apply Kubernetes manifests
  ansible.builtin.command:
    cmd: minikube kubectl -- apply -f /opt/sre-challenge/kubernetes/
  become: false
  changed_when: false

- name: Create application directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/scripts
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Place dashboard script
  ansible.builtin.copy:
    src: files/scripts/dashboard.sh
    dest: /home/{{ ansible_user }}/scripts/dashboard.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  notify: restart dashboard service

- name: Enable and start the dashboard service
  ansible.builtin.command:
    cmd: minikube addons enable dashboard
  become: false

- name: Make application run by systemd service
  ansible.builtin.template:
    src: files/scripts/dashboard.service.j2
    dest: /etc/systemd/system/dashboard.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart dashboard service

- name: Enable and start the application service
  ansible.builtin.systemd:
    name: dashboard.service
    state: started
    enabled: true
    daemon_reload: yes
  become: true

- name: Check minikube service
  ansible.builtin.command:
    cmd: systemctl is-active minikube.service
  register: minikube_service
  changed_when: false
  failed_when: false

- name: Check dashboard service
  ansible.builtin.command:
    cmd: systemctl is-active dashboard.service
  register: dashboard_service
  changed_when: false
  failed_when: false

- name: Show service status
  ansible.builtin.debug:
    msg: "minikube.service is {{ 'running' if minikube_service.stdout == 'active' else 'not running' }}"

- name: Show service status
  ansible.builtin.debug:
    msg: "dashboard.service is {{ 'running' if dashboard_service.stdout == 'active' else 'not running' }}"