apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: sqlite-pv
  resources:
    requests:
      storage: 1Gi