---
- name: Update and upgrade all packages on all hosts
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        name: "*"
        state: latest

    - name: upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        force: yes

- name: install SQLlite
  hosts: all
  become: true
  gather_facts: false

  roles:
    - sqlite        

- name: Configure webapp
  hosts: traditional
  become: true
  gather_facts: false

  roles:
    - traditional-webapp

- name: Configure minikube
  hosts: minikube
  become: true
  gather_facts: false

  roles:
    - minikube


  
