---
- name: Check if database exists
  ansible.builtin.stat:
    path: /var/lib/sre-challenge/database.db
  register: database_file

- name: Install SQLite
  ansible.builtin.apt:
    name: sqlite3
    state: present
    update_cache: true

- name: Create SQLite database directory
  ansible.builtin.file:
    path: /var/lib/sre-challenge
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Copy SQLite database
  ansible.builtin.copy:
    src: database.db
    dest: /var/lib/sre-challenge/database.db
    owner: root
    group: root
    mode: '0644'
  when: not database_file.stat.exists