---
name: Update application

on:
  push:
    branches:
      - feature/app

jobs:
  build-en-deploy:
    runs-on: self-hosted

    

    steps:
      - name: Haal repository op
        uses: actions/checkout@v4
           
      - name: Voer Ansible-playbook uit
        working-directory: ./ansible
        env:
          VAULT_PASS: ${{ secrets.ansible_vault_password }}
        run: |
          echo "$VAULT_PASS" > /tmp/vault_pass.txt && \
          chmod 600 /tmp/vault_pass.txt && \
          ansible-playbook -i inventory.ini update-app.yaml --vault-password-file /tmp/vault_pass.txt && \
          rm -f /tmp/vault_pass.txt


