---
name: Deploy infrastructure and configure hosts

on:
  workflow_dispatch:

jobs:
  build-en-deploy:
    runs-on: self-hosted

    env:
      TF_VAR_api_proxmox: ${{ secrets.proxmox_api }}
      TF_VAR_prox_user: ${{ secrets.prox_user }}
      TF_VAR_prox_pass: ${{ secrets.prox_pass }}
      TF_VAR_ubuntu_user: ${{ secrets.ubuntu_user }}
      TF_VAR_ubuntu_pass: ${{ secrets.ubuntu_pass }}
      TF_VAR_ssh: ${{ secrets.sshpub_key }}
      TF_VAR_vlan: ${{ secrets.vlan }}
      TF_VAR_prefix: ${{ secrets.prefix }}
      TF_TOKEN_app_terraform_io: ${{ secrets.hcp_token }}
      K8S_APP_SCECRET: ${{ secrets.app_secret }}
      VAULT_PASS: ${{ secrets.ansible_vault_password }}

    steps:
      - name: Get repository 
        uses: actions/checkout@v4
      
      - name: Terraform initialiseren
        working-directory: ./terraform
        run: terraform init

      - name: Terraform validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Add new inventory to git workspace
        working-directory: ./ansible
        run: |
           cp inventories/inventory.ini "$GITHUB_WORKSPACE/ansible/inventory.ini"

      - name: Run playbook
        working-directory: ./ansible
        run: |
          echo "$VAULT_PASS" > /tmp/vault_pass.txt && \
          chmod 600 /tmp/vault_pass.txt && \
          ansible-playbook -i inventories/inventory.ini playbooks/playbook.yaml --vault-password-file /tmp/vault_pass.txt && \
          rm -f /tmp/vault_pass.txt

